on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: '8.6'
      - name: Setop XVFB for GUI support 
        uses: coactions/setup-xvfb@v1.0.1
      - name: Run Unit Tests
        run: raco test tests-github.rkt